[package]
name = "darmok-postgres-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
darmok-types = { workspace = true }
darmok-execute = { workspace = true }
darmok-catalog = { workspace = true }
darmok-protocol = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }

[[test]]
name = "schema_routing"
path = "schema_routing.rs"

[[test]]
name = "native_values"
path = "native_values.rs"

[[test]]
name = "native_parameters"
path = "native_parameters.rs"

[[test]]
name = "native_catalog"
path = "native_catalog.rs"
