use darmok_catalog::{
    CatalogError, ColumnGeneration, ColumnIdentity, NativeCatalog, NativeColumn, RelationKind,
    RelationPersistence, TypeKind, read_native_relations,
};
use darmok_execute::decode_native_row_utc;
use darmok_types::Value;
use tokio_postgres::{Client, GenericClient, NoTls, types::Type};

async fn database_client() -> (
    Client,
    tokio::task::JoinHandle<Result<(), tokio_postgres::Error>>,
) {
    let url = std::env::var("DARMOK_TEST_DATABASE_URL")
        .expect("DARMOK_TEST_DATABASE_URL must point to a disposable PostgreSQL test database");
    let (client, connection) = tokio_postgres::connect(&url, NoTls).await.unwrap();
    (client, tokio::spawn(connection))
}

async fn relation_oid<C: GenericClient + Sync>(client: &C, name: &str) -> u32 {
    client
        .query_one("SELECT $1::text::regclass::oid", &[&name])
        .await
        .unwrap()
        .get(0)
}

fn column<'a>(catalog: &'a NativeCatalog, oid: u32, name: &str) -> &'a NativeColumn {
    catalog.relations[&oid]
        .columns
        .iter()
        .find(|column| column.name == name)
        .unwrap()
}

#[tokio::test]
async fn quoted_native_definitions_keep_attributes_without_inventing_mysql_metadata() {
    let (mut client, connection) = database_client().await;
    let tx = client.transaction().await.unwrap();
    tx.batch_execute(
        r#"CREATE SCHEMA "Catalog Case";
        CREATE TABLE "Catalog Case"."Product.Set" (
            "ID" bigint GENERATED ALWAYS AS IDENTITY,
            "Old" integer,
            "Label" varchar(12) COLLATE "C" NOT NULL DEFAULT 'fixture',
            "Amount" numeric(8,4),
            "Stamp" timestamp(3),
            "Clock" time(4),
            "Encoded" bytea,
            "Calc" bigint GENERATED ALWAYS AS ("ID" + 1) STORED,
            "Other ID" bigint GENERATED BY DEFAULT AS IDENTITY,
            "分析" char(6),
            "Rounded" numeric(8,-2),
            "Small" numeric(2,4)
        );
        ALTER TABLE "Catalog Case"."Product.Set" DROP COLUMN "Old";"#,
    )
    .await
    .unwrap();
    let oid = relation_oid(&tx, "\"Catalog Case\".\"Product.Set\"").await;
    let catalog = read_native_relations(&tx, &[oid, oid]).await.unwrap();
    assert_eq!(catalog.relations.len(), 1);
    let relation = &catalog.relations[&oid];
    assert_eq!(relation.oid, oid);
    assert_eq!(relation.schema_name, "Catalog Case");
    assert_eq!(relation.name, "Product.Set");
    assert_eq!(relation.kind, RelationKind::Table);
    assert_eq!(relation.persistence, RelationPersistence::Permanent);
    assert!(!relation.is_partition);
    assert_eq!(
        relation
            .columns
            .iter()
            .map(|c| c.attribute_number)
            .collect::<Vec<_>>(),
        vec![1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    );
    assert_eq!(column(&catalog, oid, "ID").identity, ColumnIdentity::Always);
    assert_eq!(
        column(&catalog, oid, "Other ID").identity,
        ColumnIdentity::ByDefault
    );
    assert!(!column(&catalog, oid, "ID").has_expression);
    assert_eq!(
        column(&catalog, oid, "Calc").generation,
        ColumnGeneration::Stored
    );
    assert!(column(&catalog, oid, "Calc").has_expression);
    assert_eq!(
        column(&catalog, oid, "Label").generation,
        ColumnGeneration::None
    );
    assert_eq!(
        column(&catalog, oid, "Label").identity,
        ColumnIdentity::None
    );
    assert!(column(&catalog, oid, "Label").has_expression);
    assert!(column(&catalog, oid, "Label").not_null_constraint);
    assert!(column(&catalog, oid, "ID").not_null_constraint);
    assert!(!column(&catalog, oid, "Amount").not_null_constraint);
    assert!(!column(&catalog, oid, "Amount").has_expression);
    assert_eq!(column(&catalog, oid, "Label").type_modifier, 12 + 4);
    assert_eq!(
        column(&catalog, oid, "Amount").type_modifier,
        (8 << 16) + 4 + 4
    );
    assert_eq!(
        column(&catalog, oid, "Rounded").type_modifier,
        (8 << 16) + 2046 + 4
    );
    assert_eq!(
        column(&catalog, oid, "Small").type_modifier,
        (2 << 16) + 4 + 4
    );
    assert_eq!(column(&catalog, oid, "Stamp").type_modifier, 3);
    assert_eq!(column(&catalog, oid, "Clock").type_modifier, 4);
    assert_eq!(column(&catalog, oid, "Encoded").type_modifier, -1);
    assert_eq!(column(&catalog, oid, "分析").type_modifier, 6 + 4);
    let c_collation: u32 = tx
        .query_one("SELECT 'pg_catalog.\"C\"'::regcollation::oid", &[])
        .await
        .unwrap()
        .get(0);
    assert_eq!(
        column(&catalog, oid, "Label").collation_oid,
        Some(c_collation)
    );
    assert_eq!(column(&catalog, oid, "Encoded").collation_oid, None);
    assert_eq!(
        column(&catalog, oid, "Encoded").declared_type_oid,
        Type::BYTEA.oid()
    );
    assert_eq!(catalog.types.len(), 7);
    for native_type in catalog.types.values() {
        assert_eq!(native_type.schema_name, "pg_catalog");
        assert_eq!(native_type.kind, TypeKind::Base);
        assert!(native_type.domain.is_none());
    }
    let row = tx
        .query_one(
            r#"INSERT INTO "Catalog Case"."Product.Set" ("Amount") VALUES (12.3400)
            RETURNING "ID", "Calc", "Label", "Amount""#,
            &[],
        )
        .await
        .unwrap();
    assert_eq!(
        decode_native_row_utc(&row).unwrap(),
        vec![
            Value::Int(1),
            Value::Int(2),
            Value::String("fixture".into()),
            Value::Decimal("12.3400".into())
        ]
    );
    tx.rollback().await.unwrap();
    drop(client);
    connection.await.unwrap().unwrap();
}

#[tokio::test]
async fn declared_domains_and_other_native_types_keep_their_own_identity() {
    let (mut client, connection) = database_client().await;
    let tx = client.transaction().await.unwrap();
    tx.batch_execute(
        r#"CREATE TEMP TABLE catalog_anchor ();
        CREATE DOMAIN pg_temp."Native Amount" AS numeric(8,4)
            NOT NULL DEFAULT 12.3400 CHECK (VALUE > 0);
        CREATE DOMAIN pg_temp."Wrapped Amount" AS pg_temp."Native Amount";
        CREATE DOMAIN pg_temp."Native Array" AS integer[][];
        CREATE TYPE pg_temp.numeric AS ENUM ('one', 'two');
        CREATE TYPE pg_temp.native_pair AS (id integer, label text);
        CREATE TEMP TABLE catalog_domains (
            amount pg_temp."Wrapped Amount",
            direct pg_temp."Native Amount",
            list pg_temp."Native Array",
            ordinary numeric,
            custom pg_temp.numeric,
            span int4range,
            spans int4multirange,
            pair pg_temp.native_pair,
            matrix integer[][]
        );"#,
    )
    .await
    .unwrap();
    let oid = relation_oid(&tx, "pg_temp.catalog_domains").await;
    let catalog = read_native_relations(&tx, &[oid]).await.unwrap();
    let amount = column(&catalog, oid, "amount");
    let direct = column(&catalog, oid, "direct");
    assert_ne!(amount.declared_type_oid, direct.declared_type_oid);
    assert!(!amount.not_null_constraint);
    assert!(!direct.not_null_constraint);
    assert!(!direct.has_expression);
    let wrapped = &catalog.types[&amount.declared_type_oid];
    let domain = &catalog.types[&direct.declared_type_oid];
    assert_eq!(wrapped.kind, TypeKind::Domain);
    assert_eq!(wrapped.name, "Wrapped Amount");
    assert_eq!(wrapped.domain.unwrap().base_type_oid, domain.oid);
    assert_eq!(domain.name, "Native Amount");
    assert!(domain.domain.unwrap().not_null_constraint);
    assert_eq!(domain.domain.unwrap().base_type_oid, Type::NUMERIC.oid());
    assert_eq!(domain.domain.unwrap().base_type_modifier, (8 << 16) + 4 + 4);
    assert_eq!(catalog.types[&Type::NUMERIC.oid()].kind, TypeKind::Base);
    assert_eq!(column(&catalog, oid, "ordinary").type_modifier, -1);
    let array_domain = &catalog.types[&column(&catalog, oid, "list").declared_type_oid];
    assert_eq!(
        array_domain.domain.unwrap().base_type_oid,
        Type::INT4_ARRAY.oid()
    );
    assert_eq!(array_domain.domain.unwrap().array_dimensions, 2);
    let array = &catalog.types[&Type::INT4_ARRAY.oid()];
    assert_eq!(array.category, b'A');
    assert_eq!(array.element_type_oid, Some(Type::INT4.oid()));
    // A subscripting element is a reference, not an implicit scalar fallback.
    assert!(!catalog.types.contains_key(&Type::INT4.oid()));
    assert_eq!(column(&catalog, oid, "matrix").array_dimensions, 2);
    let custom = &catalog.types[&column(&catalog, oid, "custom").declared_type_oid];
    assert_eq!(custom.name, "numeric");
    assert_eq!(custom.kind, TypeKind::Enum);
    assert_ne!(custom.oid, Type::NUMERIC.oid());
    assert_eq!(custom.schema_name, catalog.relations[&oid].schema_name);
    assert_eq!(
        catalog.types[&column(&catalog, oid, "span").declared_type_oid].kind,
        TypeKind::Range
    );
    assert_eq!(
        catalog.types[&column(&catalog, oid, "spans").declared_type_oid].kind,
        TypeKind::Multirange
    );
    assert_eq!(
        catalog.types[&column(&catalog, oid, "pair").declared_type_oid].kind,
        TypeKind::Composite
    );
    let statement = tx
        .prepare("SELECT amount, direct FROM catalog_domains")
        .await
        .unwrap();
    for reported in statement.columns() {
        assert_eq!(reported.type_(), &Type::NUMERIC);
        assert_eq!(reported.type_modifier(), (8 << 16) + 4 + 4);
        assert_eq!(reported.table_oid(), Some(oid));
    }
    assert_ne!(
        amount.declared_type_oid,
        statement.columns()[0].type_().oid()
    );
    tx.rollback().await.unwrap();
    drop(client);
    connection.await.unwrap().unwrap();
}

#[tokio::test]
async fn relation_kinds_and_temporary_shadowing_are_native_oid_facts() {
    let (mut client, connection) = database_client().await;
    let tx = client.transaction().await.unwrap();
    tx.batch_execute(
        r#"CREATE SCHEMA "Catalog Kinds";
        SET LOCAL search_path TO "Catalog Kinds";
        CREATE TABLE base (id integer, label text);
        CREATE TEMP TABLE base (id integer);
        CREATE UNLOGGED TABLE unlogged (id integer);
        CREATE VIEW native_view AS SELECT id FROM "Catalog Kinds".base;
        CREATE MATERIALIZED VIEW native_materialized AS
            SELECT id FROM "Catalog Kinds".base WITH NO DATA;
        CREATE SEQUENCE native_sequence;
        CREATE TYPE native_composite AS (id integer);
        CREATE TABLE native_partitioned (id integer) PARTITION BY RANGE (id);
        CREATE TABLE native_partition PARTITION OF native_partitioned FOR VALUES FROM (0) TO (10);
        CREATE INDEX native_index ON "Catalog Kinds".base (id);
        CREATE INDEX native_partitioned_index ON native_partitioned (id);"#,
    )
    .await
    .unwrap();
    let cases = [
        (
            "\"Catalog Kinds\".base",
            RelationKind::Table,
            RelationPersistence::Permanent,
        ),
        (
            "pg_temp.base",
            RelationKind::Table,
            RelationPersistence::Temporary,
        ),
        (
            "unlogged",
            RelationKind::Table,
            RelationPersistence::Unlogged,
        ),
        (
            "native_view",
            RelationKind::View,
            RelationPersistence::Permanent,
        ),
        (
            "native_materialized",
            RelationKind::MaterializedView,
            RelationPersistence::Permanent,
        ),
        (
            "native_sequence",
            RelationKind::Sequence,
            RelationPersistence::Permanent,
        ),
        (
            "native_composite",
            RelationKind::Composite,
            RelationPersistence::Permanent,
        ),
        (
            "native_partitioned",
            RelationKind::PartitionedTable,
            RelationPersistence::Permanent,
        ),
        (
            "native_partition",
            RelationKind::Table,
            RelationPersistence::Permanent,
        ),
        (
            "native_index",
            RelationKind::Index,
            RelationPersistence::Permanent,
        ),
        (
            "native_partitioned_index",
            RelationKind::PartitionedIndex,
            RelationPersistence::Permanent,
        ),
    ];
    let mut oids = Vec::new();
    for (name, _, _) in &cases {
        oids.push(relation_oid(&tx, name).await);
    }
    let toast_oid: u32 = tx
        .query_one(
            "SELECT reltoastrelid FROM pg_class WHERE oid = $1",
            &[&oids[0]],
        )
        .await
        .unwrap()
        .get(0);
    assert_ne!(toast_oid, 0);
    oids.push(toast_oid);
    let catalog = read_native_relations(&tx, &oids).await.unwrap();
    assert_eq!(catalog.relations.len(), cases.len() + 1);
    for ((_, kind, persistence), oid) in cases.iter().zip(&oids) {
        let relation = &catalog.relations[oid];
        assert_eq!(relation.kind, *kind);
        assert_eq!(relation.persistence, *persistence);
    }
    assert_eq!(catalog.relations[&toast_oid].kind, RelationKind::Toast);
    assert!(catalog.relations[&oids[8]].is_partition);
    assert!(!catalog.relations[&oids[7]].is_partition);
    let temporary = &catalog.relations[&oids[1]];
    assert_eq!(temporary.name, "base");
    assert_ne!(temporary.schema_oid, catalog.relations[&oids[0]].schema_oid);
    let temporary_statement = tx.prepare("SELECT id FROM base").await.unwrap();
    assert_eq!(temporary_statement.columns()[0].table_oid(), Some(oids[1]));
    let permanent_statement = tx
        .prepare("SELECT id FROM \"Catalog Kinds\".base")
        .await
        .unwrap();
    assert_eq!(permanent_statement.columns()[0].table_oid(), Some(oids[0]));
    tx.rollback().await.unwrap();
    drop(client);
    connection.await.unwrap().unwrap();
}

#[tokio::test]
async fn fresh_reads_observe_external_ddl_and_transaction_local_changes() {
    let (mut client, connection) = database_client().await;
    let (external, external_connection) = database_client().await;
    let backend_pid: i32 = client
        .query_one("SELECT pg_backend_pid()", &[])
        .await
        .unwrap()
        .get(0);
    let schema = format!("darmok_catalog_{backend_pid}");
    let setup = format!(
        "CREATE SCHEMA {schema}; SET search_path TO {schema};
         CREATE TABLE current (a integer, b text, c numeric(8,4));"
    );
    external.batch_execute(&setup).await.unwrap();
    client
        .batch_execute(&format!("SET search_path TO {schema}"))
        .await
        .unwrap();
    let original_oid = relation_oid(&client, "current").await;
    let initial = read_native_relations(&client, &[original_oid])
        .await
        .unwrap();
    assert_eq!(
        column(&initial, original_oid, "b").declared_type_oid,
        Type::TEXT.oid()
    );
    external
        .batch_execute(
            "ALTER TABLE current RENAME COLUMN c TO \"New Amount\";
         ALTER TABLE current ALTER COLUMN b TYPE varchar(24);
         ALTER TABLE current ALTER COLUMN b SET DEFAULT 'updated';
         ALTER TABLE current DROP COLUMN a;
         ALTER TABLE current ADD COLUMN d numeric(8,-2);
         ALTER TABLE current RENAME TO \"Fresh Name\";",
        )
        .await
        .unwrap();
    let changed = read_native_relations(&client, &[original_oid])
        .await
        .unwrap();
    assert_eq!(changed.relations[&original_oid].name, "Fresh Name");
    assert_eq!(
        column(&changed, original_oid, "b").declared_type_oid,
        Type::VARCHAR.oid()
    );
    assert_eq!(column(&changed, original_oid, "b").type_modifier, 24 + 4);
    assert!(column(&changed, original_oid, "b").has_expression);
    assert_eq!(
        column(&changed, original_oid, "New Amount").attribute_number,
        3
    );
    assert_eq!(column(&changed, original_oid, "d").attribute_number, 4);
    let tx = client.transaction().await.unwrap();
    tx.batch_execute("ALTER TABLE \"Fresh Name\" ADD COLUMN local boolean")
        .await
        .unwrap();
    let own_ddl = read_native_relations(&tx, &[original_oid]).await.unwrap();
    assert_eq!(
        column(&own_ddl, original_oid, "local").declared_type_oid,
        Type::BOOL.oid()
    );
    tx.rollback().await.unwrap();
    assert_eq!(
        read_native_relations(&client, &[original_oid])
            .await
            .unwrap(),
        changed
    );
    external
        .batch_execute(
            "DROP TABLE \"Fresh Name\"; CREATE TABLE \"Fresh Name\" (replacement bigint)",
        )
        .await
        .unwrap();
    let replacement_oid = relation_oid(&client, "\"Fresh Name\"").await;
    assert_ne!(replacement_oid, original_oid);
    assert!(
        matches!(read_native_relations(&client, &[original_oid]).await, Err(CatalogError::MissingRelation { oid }) if oid == original_oid)
    );
    assert!(matches!(
        read_native_relations(&client, &[replacement_oid, 0]).await,
        Err(CatalogError::MissingRelation { oid: 0 })
    ));
    let replacement = read_native_relations(&client, &[replacement_oid])
        .await
        .unwrap();
    assert_eq!(
        column(&replacement, replacement_oid, "replacement").declared_type_oid,
        Type::INT8.oid()
    );
    external
        .batch_execute(&format!("DROP SCHEMA {schema} CASCADE"))
        .await
        .unwrap();
    drop(client);
    drop(external);
    connection.await.unwrap().unwrap();
    external_connection.await.unwrap().unwrap();
}

#[tokio::test]
async fn zero_column_relations_and_empty_requests_are_distinct_from_missing_oids() {
    let (mut client, connection) = database_client().await;
    let tx = client.transaction().await.unwrap();
    tx.batch_execute("CREATE TEMP TABLE catalog_empty ()")
        .await
        .unwrap();
    let oid = relation_oid(&tx, "pg_temp.catalog_empty").await;
    let catalog = read_native_relations(&tx, &[oid]).await.unwrap();
    assert_eq!(catalog.relations.len(), 1);
    assert!(catalog.relations[&oid].columns.is_empty());
    assert!(catalog.types.is_empty());
    assert!(matches!(
        read_native_relations(&tx, &[0]).await,
        Err(CatalogError::MissingRelation { oid: 0 })
    ));
    assert_eq!(
        read_native_relations(&tx, &[]).await.unwrap(),
        NativeCatalog::default()
    );
    // An empty request succeeds even in an aborted transaction, proving it
    // does not issue SQL. Ordinary backend errors still require rollback.
    assert!(
        tx.batch_execute("SELECT 'ordinary-error'::integer")
            .await
            .is_err()
    );
    assert_eq!(
        read_native_relations(&tx, &[]).await.unwrap(),
        NativeCatalog::default()
    );
    assert!(
        matches!(read_native_relations(&tx, &[oid]).await, Err(CatalogError::Postgres(error)) if error.code() == Some(&tokio_postgres::error::SqlState::IN_FAILED_SQL_TRANSACTION))
    );
    tx.rollback().await.unwrap();
    drop(client);
    connection.await.unwrap().unwrap();
}

#[tokio::test]
async fn fresh_reads_honor_the_callers_repeatable_read_snapshot() {
    let (mut client, connection) = database_client().await;
    let (external, external_connection) = database_client().await;
    let backend_pid: i32 = client
        .query_one("SELECT pg_backend_pid()", &[])
        .await
        .unwrap()
        .get(0);
    let schema = format!("darmok_catalog_repeatable_{backend_pid}");
    external
        .batch_execute(&format!(
            "CREATE SCHEMA {schema}; SET search_path TO {schema};
             CREATE TABLE snapshot_table (original text);"
        ))
        .await
        .unwrap();
    let oid = relation_oid(&external, "snapshot_table").await;
    let tx = client
        .build_transaction()
        .isolation_level(tokio_postgres::IsolationLevel::RepeatableRead)
        .start()
        .await
        .unwrap();
    let before = read_native_relations(&tx, &[oid]).await.unwrap();
    assert_eq!(
        column(&before, oid, "original").declared_type_oid,
        Type::TEXT.oid()
    );
    external
        .batch_execute(
            "ALTER TABLE snapshot_table ALTER COLUMN original TYPE varchar(20);
             ALTER TABLE snapshot_table RENAME COLUMN original TO changed;",
        )
        .await
        .unwrap();
    // There is no proxy cache, but native Repeatable Read still retains the
    // transaction's earlier catalog snapshot after this committed change.
    assert_eq!(read_native_relations(&tx, &[oid]).await.unwrap(), before);
    tx.commit().await.unwrap();
    let after = read_native_relations(&client, &[oid]).await.unwrap();
    assert_eq!(
        column(&after, oid, "changed").declared_type_oid,
        Type::VARCHAR.oid()
    );
    assert_eq!(column(&after, oid, "changed").type_modifier, 20 + 4);
    external
        .batch_execute(&format!("DROP SCHEMA {schema} CASCADE"))
        .await
        .unwrap();
    drop(client);
    drop(external);
    connection.await.unwrap().unwrap();
    external_connection.await.unwrap().unwrap();
}

#[tokio::test]
async fn constraints_and_projection_nullability_remain_separate_facts() {
    let (mut client, connection) = database_client().await;
    let tx = client.transaction().await.unwrap();
    tx.batch_execute(
        "CREATE TEMP TABLE catalog_left (id integer NOT NULL);
         CREATE TEMP TABLE catalog_right (id integer NOT NULL);
         INSERT INTO catalog_left VALUES (1);
         CREATE TEMP TABLE catalog_generated (id integer,
             stored integer GENERATED ALWAYS AS (id + 1) STORED);",
    )
    .await
    .unwrap();
    let left_oid = relation_oid(&tx, "pg_temp.catalog_left").await;
    let right_oid = relation_oid(&tx, "pg_temp.catalog_right").await;
    let generated_oid = relation_oid(&tx, "pg_temp.catalog_generated").await;
    let catalog = read_native_relations(&tx, &[right_oid, left_oid])
        .await
        .unwrap();
    assert!(column(&catalog, left_oid, "id").not_null_constraint);
    assert!(column(&catalog, right_oid, "id").not_null_constraint);
    let statement = tx
        .prepare(
            "SELECT l.id AS \"Left Id\", r.id AS \"Right Id\", r.id + 1 AS expression
         FROM catalog_left l LEFT JOIN catalog_right r ON l.id = r.id",
        )
        .await
        .unwrap();
    assert_eq!(statement.columns()[0].name(), "Left Id");
    assert_eq!(statement.columns()[0].table_oid(), Some(left_oid));
    assert_eq!(statement.columns()[1].table_oid(), Some(right_oid));
    assert_eq!(statement.columns()[1].column_id(), Some(1));
    assert_eq!(statement.columns()[2].table_oid(), None);
    let row = tx.query_one(&statement, &[]).await.unwrap();
    assert_eq!(
        decode_native_row_utc(&row).unwrap(),
        vec![Value::Int(1), Value::Null, Value::Null]
    );
    let version: i32 = tx
        .query_one("SELECT current_setting('server_version_num')::integer", &[])
        .await
        .unwrap()
        .get(0);
    assert!(
        (170000..190000).contains(&version),
        "fixture requires PostgreSQL 17 or 18"
    );
    if version >= 180000 {
        tx.batch_execute(
            "ALTER TABLE catalog_generated ADD COLUMN virtual integer
                 GENERATED ALWAYS AS (id + 2) VIRTUAL;
             INSERT INTO catalog_generated (id) VALUES (NULL);
             ALTER TABLE catalog_generated ADD CONSTRAINT native_nn NOT NULL id NOT VALID;",
        )
        .await
        .unwrap();
        let generated = read_native_relations(&tx, &[generated_oid]).await.unwrap();
        assert_eq!(
            column(&generated, generated_oid, "virtual").generation,
            ColumnGeneration::Virtual
        );
        assert!(column(&generated, generated_oid, "virtual").has_expression);
        assert!(column(&generated, generated_oid, "id").not_null_constraint);
        let validated: bool = tx.query_one("SELECT convalidated FROM pg_constraint WHERE conrelid = $1 AND conname = 'native_nn'", &[&generated_oid]).await.unwrap().get(0);
        assert!(!validated);
        let null_count: i64 = tx
            .query_one(
                "SELECT count(*) FROM catalog_generated WHERE id IS NULL",
                &[],
            )
            .await
            .unwrap()
            .get(0);
        assert_eq!(null_count, 1);
    } else {
        let generated = read_native_relations(&tx, &[generated_oid]).await.unwrap();
        assert_eq!(
            column(&generated, generated_oid, "stored").generation,
            ColumnGeneration::Stored
        );
        assert!(!column(&generated, generated_oid, "id").not_null_constraint);
    }
    tx.rollback().await.unwrap();
    drop(client);
    connection.await.unwrap().unwrap();
}
