[package]
name = "darmok-execute"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
darmok-types = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tokio-postgres = { workspace = true, features = ["with-chrono-0_4"] }
